INSERT INTO quiz.pergunta (ds_pergunta) VALUES ('Normalmente, quantos litros de sangue uma pessoa tem? Em média, quantos são retirados numa doação de sangue?');
INSERT INTO quiz.pergunta (ds_pergunta) VALUES ('De quem é a famosa frase “Penso, logo existo”?');
INSERT INTO quiz.pergunta (ds_pergunta) VALUES ('De onde é a invenção do chuveiro elétrico?');
INSERT INTO quiz.pergunta (ds_pergunta) VALUES ('Quais o menor e o maior país do mundo?');
INSERT INTO quiz.pergunta (ds_pergunta) VALUES ('Qual o nome do presidente do Brasil que ficou conhecido como Jango?');
INSERT INTO quiz.pergunta (ds_pergunta) VALUES ('Qual o grupo em que todas as palavras foram escritas corretamente?');
INSERT INTO quiz.pergunta (ds_pergunta) VALUES ('Qual o livro mais vendido no mundo a seguir à Bíblia?');
INSERT INTO quiz.pergunta (ds_pergunta) VALUES ('Quantas casas decimais tem o número pi?');
INSERT INTO quiz.pergunta (ds_pergunta) VALUES ('Atualmente, quantos elementos químicos a tabela periódica possui?');
INSERT INTO quiz.pergunta (ds_pergunta) VALUES ('Quais os países que têm a maior e a menor expectativa de vida do mundo?');

INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Tem entre 2 a 4 litros. São retirados 450 mililitros', 1, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Tem entre 4 a 6 litros. São retirados 450 mililitros', 1, 'VERDADEIRO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Tem 10 litros. São retirados 2 litros', 1, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Tem 7 litros. São retirados 1,5 litros', 1, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Tem 0,5 litros. São retirados 0,5 litros', 1, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Platão', 2, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Galileu Galilei', 2, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Descartes', 2, 'VERDADEIRO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Sócrates', 2, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Francis Bacon', 2, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('França', 3, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Inglaterra', 3, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Brasil', 3, 'VERDADEIRO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Austrália', 3, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Itália', 3, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Vaticano e Rússia', 4, 'VERDADEIRO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Nauru e China', 4, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Mônaco e Canadá', 4, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Malta e Estados Unidos', 4, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('São Marino e Índia', 4, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Jânio Quadros', 5, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Jacinto Anjos', 5, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Getúlio Vargas', 5, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('João Figueiredo', 5, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('João Goulart', 5, 'VERDADEIRO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Asterístico, beneficiente, meteorologia, entertido', 6, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Asterisco, beneficente, meteorologia, entretido', 6, 'VERDADEIRO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Asterisco, beneficente, metereologia, entretido', 6, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Asterístico, beneficiente, metereologia, entretido', 6, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Asterisco, beneficiente, metereologia, entretido', 6, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('O Senhor dos Anéis', 7, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Dom Quixote', 7, 'VERDADEIRO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('O Pequeno Príncipe', 7, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Ela, a Feiticeira', 7, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Um Conto de Duas Cidades', 7, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Duas', 8, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Centenas', 8, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Trilhares', 8, 'VERDADEIRO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Vinte', 8, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Milhares', 8, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('113', 9, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('109', 9, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('108', 9, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('118', 9, 'VERDADEIRO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('92', 9, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Japão e Serra Leoa', 10, 'VERDADEIRO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Austrália e Afeganistão', 10, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Itália e Chade', 10, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Brasil e Congo', 10, 'FALSO');
INSERT INTO quiz.resposta (ds_resposta, nr_pergunta, in_tipo_resposta) VALUES ('Estados Unidos e Angola', 10, 'FALSO');
